import styles from "@/styles/pages/Home.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import { HubConnectionBuilder } from "@microsoft/signalr";
import { HubConnection } from "@microsoft/signalr/dist/esm/HubConnection";

const Home: NextPage = () => {
	const connection = useRef<HubConnection | null>(null);

	useEffect(() => {
		connection.current = new HubConnectionBuilder()
			.withUrl("https://localhost:7055/hubs/game")
			.build();

		connection.current.start();
		return () => {
			connection.current?.stop();
		};
	}, []);

	return (
		<>
			<Head>
				<title>Carcasonne</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main className={styles.main}>
				<button onClick={() => connection.current?.send("ReadTiles")}>
					Pososatb
				</button>
			</main>
		</>
	);
};

export default Home;
